### ISSUE TITLE
Model dropdowns shouldn't be editable

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/vscode-paver#141]
Minor UI glitch: I thought I was on another window and started typing, turns out the model dropdowns are editable, and they shouldn't be:

![Image](https://github.com/user-attachments/assets/5c4a703a-d1eb-4f0b-8231-e70d1e0cb810)

**Comment by lavanyaj3** [comment]
@deboer-tim please review the PR: https://github.com/redhat-developer/vscode-paver/pull/147

**Comment by fbricon** [comment]
Thanks @lavanyaj3
