### ISSUE TITLE
Update readme with install instructions

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-paver#93]
Now that the extension is available on the marketplace (as a pre-release), the installation instructions should be updated in the readme. Keep it simple though.

**Comment by athirakm94** [comment]
Hi @fbricon 
can please provide more information about this 
as of now the latest  readme is already updated as follows for installing extension

Step 1: Install the Extension
Open Visual Studio Code, navigate to the Extensions tab on the left sidebar, select "vscode-granite," and click "install."

The [Continue.dev](https://continue.dev/) extension will be automatically added as a dependency, if not already installed. If you installed Granite Code Assistant manually, you may need to also install the Continue extension separately.

do we need to add more intstrutions ?

**Comment by fbricon** [comment]
Actually put that on hold, we mostly need to update the name of the extension everywhere. We'll know more tomorrow.

**Comment by athirakm94** [comment]
okay @fbricon

**Comment by fbricon** [comment]
Thanks @athirakm94
